### ISSUE TITLE
Crashes everytime after a certain amount

### ISSUE THREAD

**Issue by Jan0xxx** [yandevelop/Bea#35] opened 2024-01-09 10:25 UTC
Crashing is random, sometimes instantly sometimes after 30 seconds. IPA sideloaded version.

(Also happens when not installed as duplicate)

Iphone 13 pro. iOS 17.2.1

**Comment by Jan0xxx** [comment] 2024-01-09 10:30
[BeReal-2024-01-09-112301.zip](https://github.com/yandevelop/Bea/files/13872459/BeReal-2024-01-09-112301.zip)

**Comment by hogyoku** [comment] 2024-01-09 11:35
Same for me

**Comment by yandevelop** [comment] 2024-01-09 14:02
From what I can tell from the crash log, the crash is caused by libswift_concurrency within BeReal's code itself. Try downgrading BeReal

**Comment by yandevelop** [comment] 2024-01-10 00:14
Well again, Swift is your friend here. Also i can't investigate this since BeReal doesn't crash for me

**Comment by Jan0xxx** [comment] 2024-01-10 18:07
Will stay on 1.3.3 for now. Can't seem to find a original newer (1.19 or so) BeReal IPA. It works, only the update notification is a bit annoying sometimes

**Comment by yandevelop** [comment] 2024-01-10 20:53
So wait, are you saying 1.3.3 works without crashing and 1.3.4 crashes for you? Are you using the IPA or the deb?

**Comment by Jan0xxx** [comment] 2024-01-11 12:04
> So wait, are you saying 1.3.3 works without crashing and 1.3.4 crashes for you? Are you using the IPA or the deb?

Correct. IPA (sideloaded), version 1.3.3 works correctly and 1.3.4 crashes: this is using the IPA's you provided. 

If you need more information, happy to provide

**Comment by yandevelop** [comment] 2024-01-11 13:18
Ok, so it's BeReal version 1.16.1 that works. Bea 1.3.4 ipa in the Releases tab is version 1.21.1. I'll try to provide a newer BeReal version with Bea injected

**Comment by yandevelop** [comment] 2024-01-11 13:21
Please try this IPA which is BeReal version 1.21.4 with Bea 1.3.4 injected: https://easyupload.io/sdt5t5

**Comment by Jan0xxx** [comment] 2024-01-11 13:38
Thanks for the quick reply. Crashes again, can't upload logs because I'm on mobile at the moment

**Comment by yandevelop** [comment] 2024-01-11 13:46
No worries. The cause can't be Bea however, you can check that yourself for the commits. I only changed one thing that only changes the way BeReals are getting downloaded. You can use 1.3.3 until further notice

**Comment by Jan0xxx** [comment] 2024-01-11 13:51
Will do. Thanks alot! :)

**Comment by yandevelop** [comment] 2024-02-07 18:43
Hi, please test the latest release as I finally introduced some sort of fix that fixed the crashing problems for another user! https://github.com/yandevelop/Bea/releases/tag/1.3.6

**Comment by hogyoku** [comment] 2024-02-07 19:20
Im afraid that the latest sideload version still crashes after a few seconds

**Comment by yandevelop** [comment] 2024-02-07 19:30
Can you send me the crash log?

**Comment by Jan0xxx** [comment] 2024-02-07 19:42
Will test in a few days (if still needed). Nontheless, thanks for the update!

**Comment by kadewu1** [comment] 2024-02-07 19:53
@hogyoku Please provide a crash log, and further information about how are you trying to use Bea, like;
Sideloading method
Jailbreak status
IPA or .deb file
Thanks.

**Comment by hogyoku** [comment] 2024-02-07 21:14
[BeReal-2024-02-07-221132.zip](https://github.com/yandevelop/Bea/files/14201611/BeReal-2024-02-07-221132.zip)

Sideloaded via AppDB
IPA file no jailbreak

**Comment by binnichtaktiv** [comment] 2024-02-07 21:59
> Can you send me the crash log?

works now thank you🙏🏻

**Comment by yandevelop** [comment] 2024-02-07 22:05
Great that it works for some people! Unfortunately me and @kadewu1 have discovered that the app crashing is not an issue of Bea itself but it's a sideloading issue. We are currently figuring out what else could cause the app to crash on launch.
I searched for similar issues on Reddit @hogyoku. Maybe you can find a fix there in the mean time

**Comment by hogyoku** [comment] 2024-02-08 09:27
No downloaded from github but used appdb for sideloading

**Comment by Jan0xxx** [comment] 2024-02-09 11:25
Works for me! IPA sideloaded using signulous. I think the problem is fixed now, thanks alot! :). Shall I close the issue?

**Comment by yandevelop** [comment] 2024-02-09 23:45
@eberth Yes, could you post the crashlog here?

**Comment by Quildar** [comment] 2024-02-13 09:00
Thought I might get in on this. The app consistantly crashes any time I try to download a BeReal. I can go to my BeReal and download it. So I know it has permission to access photos. It's just when ever I click your download button on a friends BeReal it instantly crashes.
iPhone 14 Pro Max
iOS 17.3.1
BeReal.1.21.4+com.yan.bea_1.3.6_iphoneos-arm_jailed.ipa + a few other versions
Have tried Sideloadly and AltServer

[AccessoryCrash-2024-02-08-115338.ips.zip](https://github.com/yandevelop/Bea/files/14258388/AccessoryCrash-2024-02-08-115338.ips.zip)

**Comment by yandevelop** [comment] 2024-02-13 13:07
Thanks for reaching out. Yes, the issue is known and I also know why this is happening, I just have to implement a fix for this. Unfortunately the crash log you sent is not the one from BeReal.

**Comment by Quildar** [comment] 2024-02-13 19:53
Sorry, haven't tried grabbing crash logs before. Sounds like you know how you're going to fix the issue. So maybe mine won't be helpful.  Think I figured out the logs though and going to drop them just in case it's helpful.

[BeReal-2024-02-13-114627.ips.zip](https://github.com/yandevelop/Bea/files/14271475/BeReal-2024-02-13-114627.ips.zip)

**Comment by 11prasicc11** [comment] 2024-02-13 19:59
greetings brother, can you help me, if I can contact you privately on instagram or e-mail

**Comment by yandevelop** [comment] 2024-02-13 20:15
Sure, dm me on Twitter via yandevelop

**Closed** 2024-03-19 10:57 UTC
