### ISSUE TITLE
Login error!

### ISSUE THREAD

**Issue by GilloDaby** [yandevelop/Bea#29] opened 2023-11-21 23:11 UTC
When I login and enter de code send to my phone. I got this error!
An internal error has occured, print and inspect the error details for more information!

I have Iphone 14 pro on IOS 17.2

Do you have any idea why this happen?

**Comment by yandevelop** [comment] 2023-11-22 07:12
Sadly no. I also can't reproduce this error. I will update you if I got any fix for this but i'm also unsure if this issue is even produced by Bea itself

**Comment by daboizmusic** [comment] 2023-12-18 07:19
same problem  
what is causing  this error?

**Comment by yandevelop** [comment] 2023-12-18 09:31
I am unable to investigate this any further. Somehow it appears to happen when some arbitrary dylib is injected, which doesn't even need to hook any classes.

**Comment by yandevelop** [comment] 2023-12-31 16:37
![image](https://github.com/yandevelop/Bea/assets/82288425/aaf99a59-4220-4fc1-a77c-c6961aebad4f)

**Comment by daboizmusic** [comment] 2024-01-03 21:25
can you make a step by step expansion?

**Comment by yandevelop** [comment] 2024-02-22 23:17
Yes, see the issue I linked above. If you're jailbroken this issue won't occur, however if you sideload the tweaked ipa using AltStore or similar, you will get this error due to mismatching bundle ID's

**Comment by InvalidPandaa** [comment] 2024-02-22 23:26
> Yes, see the issue I linked above. If you're jailbroken this issue won't occur, however if you sideload the tweaked ipa using AltStore or similar, you will get this error due to mismatching bundle ID's

Maybe you should put a note in the description regarding this issue

**Comment by yandevelop** [comment] 2024-05-27 10:06
@everyone, please try this one: https://easyupload.io/8u2dtt. Couldn't test this myself for now unfortunately but that *might* fix the sideloading issues

**Comment by InvalidPandaa** [comment] 2024-05-27 11:30
> @everyone, please try this one: https://easyupload.io/8u2dtt. Couldn't test this myself for now unfortunately but that *might* fix the sideloading issues

Can confirm that login works now (Installed via AppDB custom cert)

**Comment by GBX-GitHub** [comment] 2024-05-27 12:55
> @everyone, please try this one: https://easyupload.io/8u2dtt. Couldn't test this myself for now unfortunately but that _might_ fix the sideloading issues

can also confirm it works flawlessly

**Closed** 2024-05-29 08:30 UTC
