### ISSUE TITLE
Cant login?

### ISSUE THREAD

**Issue by Bernarduzz** [yandevelop/Bea#21] opened 2023-09-27 17:54 UTC
I recently updated the BeFake app to version 1.3.2 on my IP 14 Pro, but I'm unable to log back into the app. It stays on the loading screen before crashing.

**Comment by yandevelop** [comment] 2023-09-27 19:42
Does Bea 1.3.1 still work? I'm unaware of this issue

**Comment by andybaws** [comment] 2023-09-27 20:04
I have the same problem

**Comment by yandevelop** [comment] 2023-09-27 20:33
Do you mind testing if Bea 1.2.2 works? Just for the sake of experimenting.Bea does not hook anything related to logging in so i'm wondering what the cause is

**Comment by cutecat5656** [comment] 2023-09-27 20:45
I just tested 1.2.2 and it's also the same issue :( I also had 1.2.2 originally this afternoon and I was logged in and all but the new posts and the discover part wouldn't load. I uninstalled and reinstalled it and tried multiple versions and now im just on the login page and it is just stuck on the loading page

**Comment by andybaws** [comment] 2023-09-27 20:55
Same issue with 1.2.2, I get an incorrect code message when I enter the code from the SMS when I try log in.

**Comment by yandevelop** [comment] 2023-09-27 21:06
@andybaws that issue is not caused by Bea itself. BeReal has issues with the SMS auth since forever (see r/BeReal_app). @cutecat5656 i don't know what causes this. Try reinstalling the app as this is most likely not caused by Bea. Everything works fine on my end. However i can upload the latest BeReal IPA with Bea injected, so that might fix some issues?

**Comment by Bernarduzz** [comment] 2023-09-28 03:38
Not sure if its related, but the problem starts when the new BeReal update rolled out a day ago. I uninstalled and reinstalled it and been in the loading screen forever.

**Comment by shadow7692** [comment] 2023-09-28 09:44
> I just tested 1.2.2 and it's also the same issue :( I also had 1.2.2 originally this afternoon and I was logged in and all but the new posts and the discover part wouldn't load. I uninstalled and reinstalled it and tried multiple versions and now im just on the login page and it is just stuck on the loading page

I went through this exact process

**Comment by ttibigno** [comment] 2023-09-29 08:20
I tried to sideload every version available on github with Sideloadly and AltStore and the SMS verification error persist. Manually tweaking the latest version (1.13.0) with 1.3.2 deb didn't resolve the issue.

**Comment by yandevelop** [comment] 2023-09-29 20:44
I'm moving this issue to #22. Will update there if I got something new

**Closed** 2024-05-29 08:30 UTC
